name: Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v2

      - name: Build frontend image
        run: |
          echo ${{ secrets.FRONTEND_ENV }} > .env
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend .

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: |
          echo ${{ secrets.BACKEND_ENV }} > .env
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend .

  push:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]

    steps:
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend

  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Pull images on virtual machine
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker compose down --remove-orphans
            echo ${{ secrets.ROOT_ENV }} > .env
            docker compose pull
            docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
            docker compose up -d
